
spring.datasource.url=jdbc:postgresql://localhost:5432/barangay
spring.datasource.username=postgres
spring.datasource.password=82219800Jeremiah

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nermamadronio@gmail.com
spring.mail.password=sduojgkekrgslvxi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


app.root.password=82219800Jeremiah!